### ISSUE TITLE
Can't setup on new servers

### ISSUE THREAD

**Issue by KuwuroUsagi** [KuwuroUsagi/temptress#24]
> 2022-08-11T18:49:20.500290+00:00 app[worker.1]: Ignoring exception in command setup:
> 2022-08-11T18:49:20.500434+00:00 app[worker.1]: Traceback (most recent call last):
> 2022-08-11T18:49:20.500460+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
> 2022-08-11T18:49:20.500460+00:00 app[worker.1]:     ret = await coro(*args, **kwargs)
> 2022-08-11T18:49:20.500469+00:00 app[worker.1]:   File "/app/Cogs/server_setup.py", line 208, in setup
> 2022-08-11T18:49:20.500470+00:00 app[worker.1]:     await prison.set_permissions(ctx.guild.get_role(d_role), view_channel=True, send_messages=True)
> 2022-08-11T18:49:20.500479+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/abc.py", line 648, in set_permissions
> 2022-08-11T18:49:20.500480+00:00 app[worker.1]:     raise InvalidArgument('target parameter must be either Member or Role')
> 2022-08-11T18:49:20.500498+00:00 app[worker.1]: discord.errors.InvalidArgument: target parameter must be either Member or Role
> 2022-08-11T18:49:20.500518+00:00 app[worker.1]: 
> 2022-08-11T18:49:20.500518+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
> 2022-08-11T18:49:20.500519+00:00 app[worker.1]: 
> 2022-08-11T18:49:20.500519+00:00 app[worker.1]: Traceback (most recent call last):
> 2022-08-11T18:49:20.500540+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
> 2022-08-11T18:49:20.500540+00:00 app[worker.1]:     await ctx.command.invoke(ctx)
> 2022-08-11T18:49:20.500549+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
> 2022-08-11T18:49:20.500549+00:00 app[worker.1]:     await injected(*ctx.args, **ctx.kwargs)
> 2022-08-11T18:49:20.500572+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
> 2022-08-11T18:49:20.500572+00:00 app[worker.1]:     raise CommandInvokeError(exc) from exc
> 2022-08-11T18:49:20.500612+00:00 app[worker.1]: discord.ext.commands.errors.CommandInvokeError: Command raised an exception: InvalidArgument: target parameter must be either Member or Role

If anyone has an idea I'm open ears but I'm pretty inept when it comes down to it

**Comment by KuwuroUsagi** [comment]
Heroku is shutting down their free tier, so the bot will go down unless i can figure out(or someone else) how to self host it without heroku dynos, I have a server ready for it, just doing some testing over the next month or two for now
